# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# FluidExamples build for CI and PR

pool: "Lite"

trigger:
- master

pr:
- master

variables:
  skipComponentGovernanceDetection: true

steps:

- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: UseNode@1
  displayName: Use Node 12.x
  inputs: 
    version: 12.x

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'sticky-storm'
    customCommand: 'run install'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'sticky-storm'
    customCommand: 'run build'
