# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# FluidExamples build for CI and PR

trigger:
- master

pr:
- master

steps:
- task: UseNode@1
  displayName: Use Node 12.x
  inputs: 
    version: 12.x
- task: Npm@1
  displayName: npm run install - sticky-storm
  inputs:
    command: 'custom'
    workingDirectory: sticky-storm
    customCommand: 'run install'
- task: Npm@2
  displayName: npm run build - sticky-storm
  inputs:
    command: 'custom'
    workingDirectory: sticky-storm
    customCommand: run build
